### PR TITLE
Added Implementation of Armstrong Number in C++

### PR DESCRIPTION
**Pull request by mokshUpadhyay57**
Hey, Aryan I have added the implementation of Armstrong Number in C++. Can you look into that?

### CODE REVIEW

**Comment by mokshUpadhyay57** [comment]
Can you comment out what the Program is all about

**Comment by aryan-upa** [comment]
Hey Moksh, can you just write a function that takes the number as input and returns boolean value indicating whether the number is Armstrong or not. No need to take input from user or even writing the main function.

for further understanding : take a look at [this](https://github.com/aryan-upa/SpecialNumberPrograms/blob/master/src/java/ArmstrongNumber.java).

**Comment by mokshUpadhyay57** [comment]
Ok  Sure, I will do that.

**Comment by mokshUpadhyay57** [comment]
Hello Aryan, I have made the changes as you said. Please look the pr

**Pull request merged**
