### PR TITLE
Added Implementation of Prime Number in C++

### PR DESCRIPTION
**Pull request by akshaygidwani404**

### CODE REVIEW

**Comment by aryan-upa** [comment]
I think you did not read the contributors guide. Pls change the code as mentioned [here](https://github.com/aryan-upa/SpecialNumberPrograms/blob/master/CONTRIBUTING.md).

**Comment by akshaygidwani404** [comment]
Okay.

**Comment by akshaygidwani404** [comment]
Okay.

**Comment by akshaygidwani404** [comment]
Updated the code as per guidelines.

**Comment by akshaygidwani404** [comment]
Thanks @aryan-upa for merging the PR. Can you add the "hacktoberfest-accepted" label to this PR #11

**Comment by akshaygidwani404** [comment]
@aryan-upa ?

**Comment by aryan-upa** [comment]
done

**Pull request merged**
